Warnings for particular tokens
omni/omnibridge-ui pull request #320
Opened 2022-02-10 07:53 UTC by dan13ram

closes #316 
closes #317 
closes #318 
closes #319

Deployed at https://sokol-omnibridge.web.app/

2022-02-10 07:55 UTC, dan13ram commented on packages/dapp/src/components/warnings/BSCGCTokenWarnings.jsx
> +export const BSCGCTokenWarnings = ({ token, noShadow = false }) => {
handles warnings as per https://github.com/omni/omnibridge-ui/issues/316

2022-02-10 07:55 UTC, dan13ram commented on packages/dapp/src/components/warnings/BSCETHTokenWarnings.jsx
> +export const BSCETHTokenWarnings = ({ token, noShadow = false }) => {
handles warnings as per https://github.com/omni/omnibridge-ui/issues/319

2022-02-10 07:56 UTC, dan13ram commented on packages/dapp/src/components/warnings/GCOriginOnBSCTokenWarning.jsx
> +export const GCOriginOnBSCTokenWarning = ({ token, noShadow = false }) => {
handles warnings as per #318

2022-02-10 07:56 UTC, dan13ram commented on packages/dapp/src/hooks/useTokenDisabled.jsx
> +export const useTokenDisabled = token => {
this hook is used to check if the token bridging is disabled for various reasons.

2022-02-10 14:01 UTC, akolotov commented
Is it possible to avoid doubled message for STAKE token?

![image](https://user-images.githubusercontent.com/20793260/153423080-4a0ad21e-1772-43a8-831c-ed3fbfbfd2bc.png)

2022-02-11 13:16 UTC, dan13ram commented
Thanks @akolotov. This should be fixed now.
![Screenshot from 2022-02-11 18:45:13](https://user-images.githubusercontent.com/10012209/153598061-cb82a3f4-9e31-48cd-b661-4ab6fe444a2c.png)

2022-02-14 15:34 UTC, akolotov requested changes
Consider to change the warning statement

2022-02-14 16:30 UTC, merged